/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '📖 Physical AI & Robotics',
      collapsible: false,
      className: 'sidebar-title',
      items: [
        {
          type: 'doc',
          id: 'preface',
          label: 'Preface',
        },
        {
          type: 'autogenerated',
          dirName: 'chapters',
        },
      ],
    },
  ],
};

export default sidebars;
